/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.security;

import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author prasanna
 */
public class SecurityGUI extends javax.swing.JFrame {

    private final int METHOD1 = 1;
    private final int METHOD2 = 2;
    /**
     * Creates new form SecurityGUI
     */
    public SecurityGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtIndexFingerWidth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMiddleFingerWidth = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRingFingerWidth = new javax.swing.JTextField();
        txtThumLength = new javax.swing.JTextField();
        txtPinkieFingerWidth = new javax.swing.JTextField();
        txtIndexFingerLength = new javax.swing.JTextField();
        txtMiddleFingerLength = new javax.swing.JTextField();
        txtRingFingerLength = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPinkieFingerLength = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtThumbWidth = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnAuth = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Security");
        setAlwaysOnTop(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setText("Middle Finger Width");

        jLabel9.setText("Ring Finger Width");

        jLabel10.setText("Pinkie Finger Width");

        jLabel1.setText("Thumb Length");

        jLabel2.setText("Index Finger Length");

        jLabel3.setText("Middle Finger Length");

        jLabel4.setText("Ring Finger Length");

        jLabel5.setText("Pinkie Finger Length");

        jLabel6.setText("Thumb Width");

        jLabel7.setText("Index Finger Width");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtThumLength)
                    .addComponent(txtIndexFingerLength)
                    .addComponent(txtMiddleFingerLength)
                    .addComponent(txtRingFingerLength)
                    .addComponent(txtPinkieFingerLength, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPinkieFingerWidth)
                    .addComponent(txtThumbWidth)
                    .addComponent(txtIndexFingerWidth)
                    .addComponent(txtMiddleFingerWidth)
                    .addComponent(txtRingFingerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtThumLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThumbWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtIndexFingerLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIndexFingerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtMiddleFingerLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMiddleFingerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtRingFingerLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRingFingerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(txtPinkieFingerLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPinkieFingerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 102, 0)));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnAuth.setText("Authenticate");
        btnAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthActionPerformed(evt);
            }
        });

        btnAdd.setText("Add User");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAuth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnHelp)
                    .addComponent(btnAuth)
                    .addComponent(btnAdd))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthActionPerformed
        // Start the auth process
        if(validate_texts()){
            // Initialize input arrays
            ArrayList<Double> arrFingerLength = initArray(METHOD1);
            ArrayList<Double> arrFingerWidth = initArray(METHOD2);
            // create measurement model
            HandMeasurements inputMeasurements = new HandMeasurements(arrFingerLength, arrFingerWidth);
            
            //create a search object
            SearchEngine engine = new SearchEngine(inputMeasurements);
            
            //check user existance for given inputs
            User user = engine.getUser();
            
            if(user==null){
                System.out.println("User Does Not Exist");
                JOptionPane.showMessageDialog(
                    this,
                    "User does not exist!",
                    "Auth Error",
                    JOptionPane.ERROR_MESSAGE
            );
            }else{
                System.out.println("User Found :- " + user.getFull_name());
                new HomeGUI(user.getFull_name()).setVisible(true);
                this.setVisible(false);
            }
        }else{
            // Show error message
            JOptionPane.showMessageDialog(
                    this,
                    "Input values may not valid",
                    "Validate Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAuthActionPerformed

    private ArrayList<Double> initArray(int method){
        ArrayList<Double> arrArray = new ArrayList<>();
        // method is for measurements options
        // method 1 --> Finger Length
        // method 2 --> Finger Width
        try{
            if(method==1){
                arrArray = new ArrayList<>();
                arrArray.add(Double.parseDouble(this.txtThumLength.getText()));
                arrArray.add(Double.parseDouble(this.txtIndexFingerLength.getText()));
                arrArray.add(Double.parseDouble(this.txtMiddleFingerLength.getText()));
                arrArray.add(Double.parseDouble(this.txtRingFingerLength.getText()));
                arrArray.add(Double.parseDouble(this.txtPinkieFingerLength.getText()));        
            }else if(method==2){
                arrArray = new ArrayList<>();
                arrArray.add(Double.parseDouble(this.txtThumbWidth.getText()));
                arrArray.add(Double.parseDouble(this.txtIndexFingerWidth.getText()));
                arrArray.add(Double.parseDouble(this.txtMiddleFingerWidth.getText()));
                arrArray.add(Double.parseDouble(this.txtRingFingerWidth.getText()));
                arrArray.add(Double.parseDouble(this.txtPinkieFingerWidth.getText()));      
            }
            return arrArray;
        }catch(Exception e){
            // Show error message
            JOptionPane.showMessageDialog(
                    this,
                    "Enter valied inputs only [" + e.toString() + "]",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return null;
        }
    }
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Exit the window and end process
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        new HelpGUI().setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Open add user dialog
        //this.setVisible(false);
        new AddUserGUI().setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed
    
    private boolean validate_texts(){
        // Check all the inputs are present before proceed
        try{
            if(this.txtThumLength.getText().replace(" ", "").equals("")){return false;}
            if(this.txtIndexFingerLength.getText().replace(" ", "").equals("")){return false;}
            if(this.txtMiddleFingerLength.getText().replace(" ", "").equals("")){return false;}
            if(this.txtRingFingerLength.getText().replace(" ", "").equals("")){return false;}
            if(this.txtPinkieFingerLength.getText().replace(" ", "").equals("")){return false;}
            if(this.txtThumbWidth.getText().replace(" ", "").equals("")){return false;}
            if(this.txtIndexFingerWidth.getText().replace(" ", "").equals("")){return false;}
            if(this.txtMiddleFingerWidth.getText().replace(" ", "").equals("")){return false;}
            if(this.txtRingFingerWidth.getText().replace(" ", "").equals("")){return false;}
            if(this.txtPinkieFingerWidth.getText().replace(" ", "").equals("")){return false;}
            //to check all inputs are valid inputs
            double test=0.0;
            test = Double.parseDouble(txtThumLength.getText().replace(" ", ""));
            test = Double.parseDouble(txtIndexFingerLength.getText().replace(" ", ""));
            test = Double.parseDouble(txtMiddleFingerLength.getText().replace(" ", ""));
            test = Double.parseDouble(txtRingFingerLength.getText().replace(" ", ""));
            test = Double.parseDouble(txtPinkieFingerLength.getText().replace(" ", ""));
            test = Double.parseDouble(txtThumbWidth.getText().replace(" ", ""));
            test = Double.parseDouble(txtIndexFingerWidth.getText().replace(" ", ""));
            test = Double.parseDouble(txtMiddleFingerWidth.getText().replace(" ", ""));
            test = Double.parseDouble(txtRingFingerWidth.getText().replace(" ", ""));
            test = Double.parseDouble(txtPinkieFingerWidth.getText().replace(" ", ""));
        }catch(Exception e){
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecurityGUI().setVisible(true);
                TextFileReader.init();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAuth;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtIndexFingerLength;
    private javax.swing.JTextField txtIndexFingerWidth;
    private javax.swing.JTextField txtMiddleFingerLength;
    private javax.swing.JTextField txtMiddleFingerWidth;
    private javax.swing.JTextField txtPinkieFingerLength;
    private javax.swing.JTextField txtPinkieFingerWidth;
    private javax.swing.JTextField txtRingFingerLength;
    private javax.swing.JTextField txtRingFingerWidth;
    private javax.swing.JTextField txtThumLength;
    private javax.swing.JTextField txtThumbWidth;
    // End of variables declaration//GEN-END:variables
}
